# Generated by Django 5.2.4 on 2025-07-20 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='report_images/'),
        ),
    ]
