# Generated by Django 5.2.4 on 2025-07-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='contact',
            field=models.CharField(default=9427028964, help_text='Email or phone number', max_length=100),
            preserve_default=False,
        ),
    ]
